Update jekyll-docker.yml

diff --git a/.github/workflows/jekyll-docker.yml b/.github/workflows/jekyll-docker.yml
--- a/.github/workflows/jekyll-docker.yml
+++ b/.github/workflows/jekyll-docker.yml
@@ -29,14 +29,7 @@ jobs:
 
     - name: Run Cypress tests and generate report
       run: |
-        try {
-          npx cypress run
-          # You can add any additional Cypress flags or commands here as needed
-          # For example: npx cypress run --headless --browser chrome
-        } catch (error) {
-          # Capture the error but don't stop the workflow
-          echo "Error during Cypress tests: $error"
-        }
+        npx cypress run || echo "Error during Cypress tests"
 
     - name: Create Cypress report artifact
       uses: actions/upload-artifact@v2
@@ -49,4 +42,3 @@ jobs:
       with:
         name: jekyll-site
         path: _site
-
