Update jekyll-docker.yml

diff --git a/.github/workflows/jekyll-docker.yml b/.github/workflows/jekyll-docker.yml
--- a/.github/workflows/jekyll-docker.yml
+++ b/.github/workflows/jekyll-docker.yml
@@ -1,43 +1,44 @@
+name: Jekyll site CI
+
 on:
   push:
-    branches:
-      - main
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
 jobs:
-  cypress-run:
-    runs-on: ubuntu-22.04
+  build:
+
+    runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+    - uses: actions/checkout@v3
+    - name: Install Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: 14
 
-      # Instala las dependencias de NPM
-      - name: Install Dependencies
-        run: npm install
+    - name: Install Cypress
+      run: npm install cypress
 
-      # Ejecuta las pruebas Cypress y genera el informe
-      - name: Cypress Run
-        run: npx cypress run
+    - name: Build the site in the jekyll/builder container
+      run: |
+        docker run \
+        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
+        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
 
-      # Genera el informe de Cucumber HTML
-      - name: Generate Cucumber HTML Report
-        run: node cucumber-html-report.js
+    - name: Run Cypress tests
+      run: |
+        npx cypress run || echo "Error during Cypress tests"
+        # Genera el informe HTML en el directorio de Cypress
+        ./generate-report.sh
 
-      # Configura el entorno para la acción gh-pages
-      - name: Set up Node
-        uses: actions/setup-node@v2
-        with:
-          node-version: 18  # Puedes ajustar la versión de Node según tus requisitos
 
-      # Publica el informe en la rama gh-pages utilizando la acción específica
-      - name: Deploy to GitHub Pages
-        run: |
-          # Ejemplo: Utiliza la acción peaceiris/actions-gh-pages
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          git checkout -b gh-pages
-          git add .
-          git commit -m "Deploy Cucumber report"
-          git push -f origin gh-pages
+    - name: Create HTML report artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: cypress-html-report
+        path: cypress-report.html # Ajusta la ruta al informe HTML generado por Cypress
 
 
 
